"""Transcript parsing for claude-performance-tracker.

Turns a Claude Code session JSONL transcript into a list of `Turn`s. This is the
single reusable parser; `signals.py` layers the friction/output signals on top,
but the turn-boundary and token-envelope logic lives here.

Key facts about the transcript format this relies on, all verified against real
transcripts rather than assumed:

  * Assistant lines duplicate — the same logical message appears several times
    with the same `message.id`, each copy repeating the cumulative usage. Token
    usage must be counted ONCE per distinct `message.id`.
  * A turn boundary is a `type=user` line that is not `isMeta`, carries no
    `toolUseResult`, and whose text is not one of the SYNTHETIC_PREFIXES below.
    Claude Code injects several `type=user` records that no human typed —
    `<task-notification>`, local-command caveats/stdout, interrupt markers. They
    are NOT prompts: counting them inflates `num_prompts` by ~19% and pollutes
    prompt-quality scoring. They fold into the turn already in progress, because
    the work they trigger belongs to the prompt that started it.
  * Subagent usage is NOT in the main transcript as sidechain records. (This
    plugin used to assume it was; `isSidechain` is false on every record of every
    real transcript checked.) A subagent's full envelope arrives in the `Agent`
    tool's `toolUseResult`: `agentId`, `agentType`, `resolvedModel`, `usage`,
    `totalToolUseCount`, `totalDurationMs` — but only once `status` is
    `completed`. A backgrounded agent's launch result is `async_launched` and
    carries no usage; it reports back later in a `<task-notification>` that
    carries only an aggregate `<subagent_tokens>` total.
  * `effort` sits at the top level of an assistant record, not inside `message`.
  * `usage.cache_creation` splits cache writes into 5m and 1h TTL buckets, which
    are billed at 1.25x and 2x input respectively — worth keeping apart.
  * There is no per-turn id, so a main turn is keyed on the user prompt's `uuid`
    and a subagent turn on `agent:<agentId>`.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from datetime import datetime, timezone

# `type=user` records Claude Code injects that no human typed. A record whose
# text starts with one of these is not a turn boundary.
SYNTHETIC_PREFIXES = (
    "<task-notification>",
    "<local-command-caveat>",
    "<local-command-stdout>",
    "<local-command-stderr>",
    "<system-reminder>",
    "[Request interrupted",
    "Caveat: The messages below were generated by the user while running local commands",
)

# How Claude Code actually records an interruption. The old detector looked for
# `toolUseResult.interrupted`, which does not exist in any real transcript, so
# the signal read zero forever.
INTERRUPT_MARKER = "[Request interrupted"

# A single gap longer than this is idle time (the user walked away, or a
# backgrounded agent was still running), not work. Capping each gap turns the
# raw first-to-last span — which produced 250-hour "runs" — into a duration that
# means something. Deliberately generous: real tool calls can take minutes.
IDLE_GAP_MS = 5 * 60 * 1000

_TASK_ID_RE = re.compile(r"<task-id>([^<]+)</task-id>")
_SUBAGENT_TOKENS_RE = re.compile(r"<subagent_tokens>\s*(\d+)\s*</subagent_tokens>")
_TOOL_USES_RE = re.compile(r"<tool_uses>\s*(\d+)\s*</tool_uses>")
_DURATION_RE = re.compile(r"<duration_ms>\s*(\d+)\s*</duration_ms>")


@dataclass
class Turn:
    turn_id: str
    seq: int
    started_at: str | None = None
    ended_at: str | None = None
    model: str | None = None
    effort: str | None = None
    query_source: str = "main"        # main | subagent
    is_prompt: bool = True            # False for subagent rows and orphan blocks
    agent_type: str | None = None
    input_tokens: int = 0
    output_tokens: int = 0
    cache_read_tokens: int = 0
    cache_creation_tokens: int = 0
    cache_creation_1h_tokens: int = 0
    total_tokens_agg: int = 0         # aggregate-only total, no per-class split
    num_tool_calls: int = 0
    active_ms: int | None = None
    prompt_text: str = ""
    _msgs: dict = field(default_factory=dict, repr=False)
    _stamps: list = field(default_factory=list, repr=False)


def parse_iso(ts: str | None) -> datetime | None:
    if not ts:
        return None
    try:
        return datetime.fromisoformat(ts.replace("Z", "+00:00"))
    except ValueError:
        return None


def duration_ms(start: str | None, end: str | None) -> int | None:
    a, b = parse_iso(start), parse_iso(end)
    if a is None or b is None:
        return None
    if a.tzinfo is None:
        a = a.replace(tzinfo=timezone.utc)
    if b.tzinfo is None:
        b = b.replace(tzinfo=timezone.utc)
    return int((b - a).total_seconds() * 1000)


def message_text(rec: dict) -> str:
    """The plain text of a record's message, whatever shape the content is in."""
    content = ((rec.get("message") or {}) if isinstance(rec.get("message"), dict)
               else {}).get("content")
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        return "\n".join(
            b.get("text", "") for b in content
            if isinstance(b, dict) and b.get("type") == "text"
        )
    return ""


def is_synthetic_prompt(text: str) -> bool:
    """True for a `type=user` record Claude Code injected rather than the human."""
    stripped = text.lstrip()
    return any(stripped.startswith(p) for p in SYNTHETIC_PREFIXES)


def _is_user_record(rec: dict) -> bool:
    """A `type=user` record carrying real message content (not a tool result)."""
    if rec.get("type") != "user" or rec.get("isMeta"):
        return False
    if rec.get("toolUseResult") is not None or "toolUseResult" in rec:
        return False
    content = (rec.get("message") or {}).get("content")
    if isinstance(content, str):
        return content.strip() != ""
    if isinstance(content, list) and content:
        first = content[0]
        return isinstance(first, dict) and first.get("type") == "text"
    return False


def _load(path: str) -> list[dict]:
    rows = []
    try:
        fh = open(path, "r", errors="replace")
    except OSError:
        return rows
    with fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            try:
                rows.append(json.loads(line))
            except json.JSONDecodeError:
                continue
    return rows


def _agent_turn(tur: dict, seq: int, ts: str | None) -> Turn | None:
    """A subagent's envelope from a completed `Agent` tool result."""
    agent_id = tur.get("agentId")
    usage = tur.get("usage")
    if not agent_id or not isinstance(usage, dict):
        return None
    cc = usage.get("cache_creation")
    cc_1h = int((cc or {}).get("ephemeral_1h_input_tokens") or 0) if isinstance(cc, dict) else 0
    dur = tur.get("totalDurationMs")
    return Turn(
        turn_id=f"agent:{agent_id}",
        seq=seq,
        started_at=ts,
        ended_at=ts,
        model=tur.get("resolvedModel"),
        query_source="subagent",
        is_prompt=False,
        agent_type=tur.get("agentType"),
        input_tokens=int(usage.get("input_tokens") or 0),
        output_tokens=int(usage.get("output_tokens") or 0),
        cache_read_tokens=int(usage.get("cache_read_input_tokens") or 0),
        cache_creation_tokens=int(usage.get("cache_creation_input_tokens") or 0),
        cache_creation_1h_tokens=cc_1h,
        num_tool_calls=int(tur.get("totalToolUseCount") or 0),
        active_ms=int(dur) if isinstance(dur, (int, float)) else None,
        prompt_text=str(tur.get("prompt") or "")[:2000],
    )


def _notification_turn(text: str, seq: int, ts: str | None) -> Turn | None:
    """Fallback envelope for a backgrounded agent that only reported an aggregate.

    Carries no per-class split, so its total lands in `total_tokens_agg` and is
    deliberately kept out of the weighted-cost maths rather than guessed at.
    """
    tid = _TASK_ID_RE.search(text)
    tok = _SUBAGENT_TOKENS_RE.search(text)
    if not tid or not tok:
        return None
    tools = _TOOL_USES_RE.search(text)
    dur = _DURATION_RE.search(text)
    return Turn(
        turn_id=f"agent:{tid.group(1)}",
        seq=seq,
        started_at=ts,
        ended_at=ts,
        query_source="subagent",
        is_prompt=False,
        total_tokens_agg=int(tok.group(1)),
        num_tool_calls=int(tools.group(1)) if tools else 0,
        active_ms=int(dur.group(1)) if dur else None,
    )


def parse_turns(path: str, include_sidechain: bool = False) -> list[Turn]:
    """Parse a transcript into main turns plus one row per subagent invocation.

    Main turns keep only the main thread's own tokens; each subagent gets its own
    row keyed on its agent id, so subagent spend is attributed without being
    folded into — or, as before, truncating — the prompt that launched it.

    `include_sidechain` is accepted for backwards compatibility and ignored:
    sidechain records do not appear in Claude Code transcripts.
    """
    rows = _load(path)
    turns: list[Turn] = []
    agents: dict[str, Turn] = {}
    cur: Turn | None = None

    def flush():
        if cur is not None and (cur._msgs or cur.total_tokens_agg):
            turns.append(cur)

    for rec in rows:
        rtype = rec.get("type")

        if _is_user_record(rec):
            text = message_text(rec)
            if is_synthetic_prompt(text):
                # Not a boundary. A task-notification may still be the only
                # record of a backgrounded agent's spend.
                nt = _notification_turn(text, len(turns), rec.get("timestamp"))
                if nt and nt.turn_id not in agents:
                    agents[nt.turn_id] = nt
                continue
            flush()
            cur = Turn(
                turn_id=rec.get("uuid") or f"turn-{len(turns)}",
                seq=len(turns),
                started_at=rec.get("timestamp"),
                prompt_text=text,
            )
            if rec.get("timestamp"):
                cur._stamps.append(rec["timestamp"])
            continue

        if rtype == "assistant":
            if cur is None:
                # Assistant work with no preceding human prompt (transcript
                # starts mid-turn, e.g. after a resume). Keep the tokens, but
                # don't let it count as a prompt.
                cur = Turn(
                    turn_id=rec.get("uuid") or f"orphan-{len(turns)}",
                    seq=len(turns),
                    started_at=rec.get("timestamp"),
                    is_prompt=False,
                )
            mid = (rec.get("message") or {}).get("id") or rec.get("uuid")
            if mid:
                cur._msgs[mid] = rec
            if rec.get("timestamp"):
                cur._stamps.append(rec["timestamp"])

        tur = rec.get("toolUseResult")
        if isinstance(tur, dict) and tur.get("agentId"):
            at = _agent_turn(tur, len(turns), rec.get("timestamp"))
            if at is not None:
                agents[at.turn_id] = at  # rich result always wins over aggregate

    flush()

    for turn in turns:
        _finalize(turn)
    return turns + list(agents.values())


def _finalize(turn: Turn) -> None:
    last_ts = None
    last_model = None
    last_effort = None
    for rec in turn._msgs.values():
        msg = rec.get("message") or {}
        usage = msg.get("usage") or {}
        turn.input_tokens += int(usage.get("input_tokens") or 0)
        turn.output_tokens += int(usage.get("output_tokens") or 0)
        turn.cache_read_tokens += int(usage.get("cache_read_input_tokens") or 0)
        turn.cache_creation_tokens += int(usage.get("cache_creation_input_tokens") or 0)
        cc = usage.get("cache_creation")
        if isinstance(cc, dict):
            turn.cache_creation_1h_tokens += int(cc.get("ephemeral_1h_input_tokens") or 0)
        content = msg.get("content")
        if isinstance(content, list):
            turn.num_tool_calls += sum(
                1 for b in content
                if isinstance(b, dict) and b.get("type") == "tool_use"
            )
        ts = rec.get("timestamp")
        if ts and (last_ts is None or ts > last_ts):
            last_ts = ts
        if msg.get("model"):
            last_model = msg["model"]
        if rec.get("effort"):
            last_effort = rec["effort"]
    turn.ended_at = last_ts
    turn.model = last_model
    turn.effort = last_effort
    turn.active_ms = _active_ms(turn._stamps)


def _active_ms(stamps: list) -> int | None:
    """Working time: the span, with each individual idle gap capped.

    Sums consecutive gaps, counting at most IDLE_GAP_MS per gap, so a turn left
    open overnight contributes its real work rather than the calendar span.
    """
    ordered = sorted(t for t in stamps if t)
    if len(ordered) < 2:
        return 0
    total = 0
    for a, b in zip(ordered, ordered[1:]):
        gap = duration_ms(a, b)
        if gap is None or gap <= 0:
            continue
        total += min(gap, IDLE_GAP_MS)
    return total
